name: flutter_architect
description: Demo application architect
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  intl: ^0.18.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  import_sorter: ^4.6.0
  lint: ^2.1.2

flutter:
  uses-material-design: true
